export const PROJECTS_RECEIVED = 'PROJECTS_RECEIVED'
export const PROJECT_CREATED = 'PROJECT_CREATED'

// Register User
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

// 施工日報表
export const CONSTRUCTION_DAILY_LIST_RECEIVED = 'CONSTRUCTION_DAILY_LIST_RECEIVED'
export const CONSTRUCTION_DAILY_CREATED = 'CONSTRUCTION_DAILY_CREATED'
